---
name: Build


on:
  workflow_call:
    inputs:
      is-release:
        type: boolean
        required: true
      python-version:
        type: string
        required: true
      version:
        type: string
        required: true


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9  # v3.5.3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@bd6b4b6205c4dbad673328db7b31b7fab9e241c0  # v4.6.1
        with: 
          python-version: ${{ inputs.python-version }}

      - name: Setup Project
        run: |
          python -m pip install --upgrade pipenv
          pipenv install

      - name: Save version
        run: |
          cat version.json | jq '. + {"version": "${{ inputs.version }}"}' > tmpVersion.json
          mv tmpVersion.json version.json

          cat version.json 

      - name: Generate tag list
        id: tag-list
        run: |
          if [[ "${{ inputs.is-release }}" == "true" ]]; then
            echo "tags=ghcr.io/flinnsolutions/bw-devops-exercise:latest,ghcr.io/flinnsolutions/bw-devops-exercise:${{ inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "tags=ghcr.io/flinnsolutions/bw-devops-exercise:${{ inputs.version }}" >> $GITHUB_OUTPUT
          fi

      - name: Login to container registry
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc  #v2.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Build & Push
        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825  # v4.1.1
        with:
          context: .
          push: true
          tags: ${{ steps.tag-list.outputs.tags }}
