---
name: _cd


on:
  workflow_call:


jobs:
  test:
    uses: ./.github/workflows/_test.yml
    with:
      python-version: "3.11"


  version:
    uses: ./.github/workflows/_version.yml


  build:
    needs:
      - version
      - test
    permissions:
      packages: write
      contents: read
    uses: ./.github/workflows/_build.yml
    with: 
      is-release: ${{ needs.version.outputs.is-release == 'true' }}
      python-version: "3.11"
      version: ${{ needs.version.outputs.version }}
        

  release:
    needs:
      - version
      - build
    permissions:
      contents: write
    uses: ./.github/workflows/_release.yml
    with:
      is-release: ${{ needs.version.outputs.is-release == 'true' }}
      version: ${{ needs.version.outputs.version }}
