---
name: Test


on:
  workflow_call:
    inputs:
      python-version:
        type: string
        default: false


jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9  # v3.5.3

      - name: Setup Python
        uses: actions/setup-python@bd6b4b6205c4dbad673328db7b31b7fab9e241c0  # v4.6.1
        with: 
          python-version: ${{ inputs.python-version }}

      - name: Setup Project
        run: |
          python -m pip install --upgrade pipenv
          pipenv install --dev

      - name: Run Unit Tests
        run: pipenv run pytest tests/unit
