---
name: CD
run-name: CD \#${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}


on:
  pull_request:
    branches:
      - main
    types: [closed]
  workflow_dispatch:
    inputs: {}


jobs:
  pr:
    runs-on: ubuntu-22.04
    outputs:
      is-merged: ${{ steps.pr.outputs.is-merged }}
    steps:
      - name: Check if closed PR is merged
        id: pr
        run: |
          if [[ "${{ github.event.pull_request.number }}" == "" ]]; then
            echo "Trigger event was not a PR"
            exit 1
          fi

          http_code=${
            curl -L \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/${{ github.event.repository }}/pulls/${{ github.event.pull_request.number }}/merge \
              -o /dev/null -w '%{http_code}' -s
          }

          if [[ "$http_code" == "204" ]]; then
            echo "is-merged=true" >> $GITHUB_OUTPUT
          else
            echo "is-merged=false" >> $GITHUB_OUTPUT
          fi


      - name: Test PR state output
        run: |
          echo "PR is merged: ${{ steps.pr.outputs.is-merged }}"
            

  test:
    if: ${{ needs.pr.outputs.is-merged == 'true' }}
    needs:
      - pr
    uses: ./.github/workflows/_test.yml
    with:
      python-version: "3.11"


  version:
    if: ${{ needs.pr.outputs.is-merged == 'true' }}
    needs:
      - pr
    uses: ./.github/workflows/_version.yml


  build:
    if: ${{ needs.pr.outputs.is-merged == 'true' }}
    needs:
      - pr
      - version
      - test
    permissions:
      packages: write
      contents: read
    uses: ./.github/workflows/_build.yml
    with: 
      is-release: ${{ needs.version.outputs.is-release == 'true' }}
      python-version: "3.11"
      version: ${{ needs.version.outputs.version }}
        

  release:
    if: ${{ needs.pr.outputs.is-merged == 'true' }}
    needs:
      - pr
      - version
      - build
    permissions:
      contents: write
    uses: ./.github/workflows/_release.yml
    with:
      is-release: ${{ needs.version.outputs.is-release == 'true' }}
      version: ${{ needs.version.outputs.version }}
