---
name: CD
run-name: "CD #${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}"


on:
  pull_request:
    branches:
      - main
    types: [closed]
  workflow_dispatch:
    inputs: {}


jobs:
  pr:
    name: Check if Closed PR is merged
    runs-on: ubuntu-22.04
    outputs:
      is-merged: ${{ steps.pr.outputs.is-merged }}
    steps:
      - name: Check if closed PR is merged
        id: pr
        run: |
          if [[ "${{ github.event.pull_request.number }}" == "" ]]; then
            echo "Trigger event was not a PR"
            exit 1
          fi

          http_code=$(
            curl -L \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/merge \
              -o /dev/null -w '%{http_code}' -s
          )

          if [[ "$http_code" == "204" ]]; then
            echo "is-merged=true" >> $GITHUB_OUTPUT
          else
            echo "is-merged=false" >> $GITHUB_OUTPUT
          fi


      - name: Test PR state output
        run: |
          echo "PR is merged: ${{ steps.pr.outputs.is-merged }}"
            

  cd-on-merge:
    if: ${{ needs.pr.outputs.is-merged == 'true' }}
    needs:
      - pr
    permissions:
      contents: write
      packages: write
    uses: ./.github/workflows/_cd-on-merge.yml
