---
name: CD
run-name: "CD"


on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs: {}


jobs:
  test:
    uses: ./.github/workflows/_test.yml
    with:
      python-version: "3.11"


  pr:
    name: Check if Closed PR is merged
    runs-on: ubuntu-22.04
    outputs:
      is-merged: ${{ steps.pr.outputs.id }}
    steps:
      - name: Get PR ID
        id: pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          commit_message=$(
            curl -s -L \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $GH_TOKEN" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }} | \
            jq -r ".commit.message"
          )
          ID=$(echo "$commit_message" | head -1 | grep -o "(#.*)" | grep -o "[0-9]*")
          echo "id=$ID" >> $GITHUB
            

  version:
    needs:
      - pr
    uses: ./.github/workflows/_version.yml
    with:
      is-release: true
      pull-request-number: ${{ needs.pr.outputs.id }}


  build:
    needs:
      - version
      - test
    permissions:
      packages: write
      contents: read
    uses: ./.github/workflows/_build.yml
    with: 
      is-release: ${{ needs.version.outputs.is-release == 'true' }}
      python-version: "3.11"
      version: ${{ needs.version.outputs.version }}
        

  release:
    needs:
      - version
      - build
    permissions:
      contents: write
    uses: ./.github/workflows/_release.yml
    with:
      is-release: ${{ needs.version.outputs.is-release == 'true' }}
      version: ${{ needs.version.outputs.version }}
