---
name: CI Feature Branch
run-name: "CI - ${{ github.event.pull_request.title }}"

on:
  pull_request: 
    types: [opened, edited, synchronize]
  workflow_dispatch: {}


jobs:
  test-unit:
    name: Run Unit Tests
    uses: ./.github/workflows/_test_unit.yml
    with:
      python-version: "3.11"
