---
name: CI
run-name: "CI - ${{ github.event.pull_request.title }}"

on:
  pull_request: 
    types: [opened, edited, synchronize]
  workflow_dispatch: {}


jobs:
  test:
    uses: ./.github/workflows/_test.yml
    with:
      python-version: "3.11"
