---
name: CI

on:
  pull_request:
    paths:
      - 'src/**'
      - 'Dockerfile'
      - 'tests/unit/**'
  workflow_dispatch:
    inputs: {}


jobs:
  test:
    uses: ./.github/workflows/_test.yml
    with:
      python-version: "3.11"
