---
name: Experiment
run-name: "Exp - ${{ github.sha }}"


on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs: {}


jobs:
  exp:
    name: experiment
    runs-on: ubuntu-22.04
    steps:
      - name: run experiment
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_ID=$(echo "${{ github.event.commits[0].message }}" | head -1 | grep -o "(#.*)" | grep -o "[0-9]*")
          gh pr view $PR_ID --json labels | jq -r ".labels"
