---
name: Experiment
run-name: "Exp - ${{ github.sha }}"


on:
  push:
    branches:
      - main
      - experiment
  workflow_dispatch:
    inputs: {}


jobs:
  exp:
    name: experiment
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9  #v3.5.3

      - name: run experiment
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          #PR_ID=$(echo "${{ github.event.commits[0].message }}" | head -1 | grep -o "(#.*)" | grep -o "[0-9]*")
          PR_ID=16
          version_tags=$(gh pr view $PR_ID --json labels | jq -r ".labels[].name" | grep "version")

          if [[ $(echo $version_tags | wc -l) -gt 1 ]]; then
              echo "multiple version labels..."
          else
              echo "only one version label"
          fi
