---
name: Experiment
run-name: "Exp - ${{ github.sha }}"


on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs: {}


jobs:
  exp:
    name: experiment
    runs-on: ubuntu-22.04
    steps:
      - name: run experiment
        run: |
          PR_ID=$(echo "${{ github.event.commits[0].message }}" | head -1 | grep -o "(#.*)" | grep -o "[0-9]*")

          pull_request=$(
            curl -L \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/${{ github.repository }}/pulls/$PR_ID
          )

          echo "$pull_request" | jq -r ".labels"
